//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlace.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPlacedVariant
    {
        public System.Guid ID { get; set; }
        public System.Guid OrderPlacedID { get; set; }
        public System.Guid VariantID { get; set; }
        public double SellingPrice { get; set; }
        public int Quantity { get; set; }
    
        public virtual OrderPlaced OrderPlaced { get; set; }
        public virtual Variant Variant { get; set; }
    }
}
