//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlace.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantPropertyValue
    {
        public int ID { get; set; }
        public System.Guid PropertyID { get; set; }
        public System.Guid ValueID { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Value Value { get; set; }
    }
}
